export const FETCH_PIZZAS = 'FETCH_PIZZAS'
export const SET_CATEGORY = 'SET_CATEGORY'
export const SET_SORTING = 'SET_SORTING'
export const SET_LOADING = 'SET_LOADING'
export const SET_SORT_BY = 'SET_SORT_BY'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const CLEAR_CART = 'CLEAR_CART'